all:
	../src/shorte.py -f user_guide.tpl -p html -t shorte

pdf:
	../src/shorte.py -f user_guide.tpl -p "html+pdf" -t shorte

merge:
	../src/shorte.py -f user_guide.tpl -p "mergefile" -t cortina_public

