all:
	../src/shorte.py -f user_guide.tpl -p html -t cortina_public

pdf:
	../src/shorte.py -f user_guide.tpl -p "html+pdf" -t cortina_public

merge:
	../src/shorte.py -f user_guide.tpl -p "mergefile" -t cortina_public

